### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by MacSergey**

### CODE REVIEW

**Review by elGendo87 — COMMENTED** [review]
Hi! Im elGendo87, im doing some of the spanish translations. I find that i made a typo in this line. It isnt "cerril" its "carril". Sorry if this isnt the place to leave this comment. I fixed the typo in crowdin anyway.

OH! Really sorry, the SHA is ca23bb43ada437d8d5d1e04858bdad464caf5d8f // I thinked that the comment would stay in the place where i saw the error. My bad.

**Comment by MacSergey** [comment]
> Hi! Im elGendo87, im doing some of the spanish translations. I find that i made a typo in this line. It isnt "cerril" its "carril". Sorry if this isnt the place to leave this comment. I fixed the typo in crowdin anyway.
> 
> OH! Really sorry, the SHA is [ca23bb4](https://github.com/MacSergey/NodeMarkup/commit/ca23bb43ada437d8d5d1e04858bdad464caf5d8f) // I thinked that the comment would stay in the place where i saw the error. My bad.

if you have fixed it on crowdin, it will be synchronized, dont warry

**Comment by MacSergey** [comment]
> Hi! Im elGendo87, im doing some of the spanish translations. I find that i made a typo in this line. It isnt "cerril" its "carril". Sorry if this isnt the place to leave this comment. I fixed the typo in crowdin anyway.
> 
> OH! Really sorry, the SHA is [ca23bb4](https://github.com/MacSergey/NodeMarkup/commit/ca23bb43ada437d8d5d1e04858bdad464caf5d8f) // I thinked that the comment would stay in the place where i saw the error. My bad.

as you can see, it is already added
https://github.com/MacSergey/NodeMarkup/pull/347/commits/858795c447e7d0dd309fee180ebd67e1806019dc

**Comment by elGendo87** [comment]
> > Hi! Im elGendo87, im doing some of the spanish translations. I find that i made a typo in this line. It isnt "cerril" its "carril". Sorry if this isnt the place to leave this comment. I fixed the typo in crowdin anyway.
> > OH! Really sorry, the SHA is [ca23bb4](https://github.com/MacSergey/NodeMarkup/commit/ca23bb43ada437d8d5d1e04858bdad464caf5d8f) // I thinked that the comment would stay in the place where i saw the error. My bad.
> 
> if you have fixed it on crowdin, it will be synchronized, dont warry

ok! perfect! i didnt know that.
thanks you a lot for this mod. is awesome.

**Pull request merged**
